version: '3'
services:
  nginx:
    container_name: some-nginx-deploy
    image: nginx:1.13
    restart: always
    ports:
      - 88:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  postgresql:
    container_name: postgresql-deploy
    image: postgres:alpine
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=db-portfolio
    ports:
      - 5432:5432
    volumes:
      - ./src/main/resources/sql/:/docker-entrypoint-initdb.d

  app:
    container_name: app-deploy
    restart: always
    build: .
    working_dir: /app
    volumes:
      - ./:/app
      - ~/.m2:/root/.m2
    ports:
      - 8084:8080
    depends_on:
      - postgresql
    command: mvn clean install -DskipTests spring-boot:run -Dspring-boot.run.profiles=docker
