create sequence COMPANY_SEQ start with 1 increment by 1;
insert into company (id,name) values ( COMPANY_SEQ.NEXTVAL,'Apple Inc.');
insert into company (id,name) values ( COMPANY_SEQ.NEXTVAL,'Thinking Machines');
insert into company (id,name) values ( COMPANY_SEQ.NEXTVAL,'RCA');
insert into company (id,name) values ( COMPANY_SEQ.NEXTVAL,'Netronics');
insert into company (id,name) values ( COMPANY_SEQ.NEXTVAL,'Tandy Corporation');
insert into company (id,name) values ( COMPANY_SEQ.NEXTVAL,'Commodore International');

create sequence COMPUTER_SEQ start with 1 increment by 1;
insert into computer (id,name,introduced,discontinued,company_id) values ( COMPUTER_SEQ.NEXTVAL,'MacBook Pro 15.4 inch',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( COMPUTER_SEQ.NEXTVAL,'MacBook Pro','2006-01-10',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( COMPUTER_SEQ.NEXTVAL,'CM-2a',null,null,2);
insert into computer (id,name,introduced,discontinued,company_id) values ( COMPUTER_SEQ.NEXTVAL,'CM-200',null,null,2);
insert into computer (id,name,introduced,discontinued,company_id) values ( COMPUTER_SEQ.NEXTVAL,'CM-5e',null,null,2);
insert into computer (id,name,introduced,discontinued,company_id) values ( COMPUTER_SEQ.NEXTVAL,'CM-5','1991-01-01',null,2);
insert into computer (id,name,introduced,discontinued,company_id) values ( COMPUTER_SEQ.NEXTVAL,'COSMAC ELF',null,null,3);
insert into computer (id,name,introduced,discontinued,company_id) values ( COMPUTER_SEQ.NEXTVAL,'COSMAC VIP','1977-01-01',null,3);
insert into computer (id,name,introduced,discontinued,company_id) values ( COMPUTER_SEQ.NEXTVAL,'ELF II','1977-01-01',null,4);
insert into computer (id,name,introduced,discontinued,company_id) values ( COMPUTER_SEQ.NEXTVAL,'TRS-80 Color Computer','1980-01-01',null,5);
insert into computer (id,name,introduced,discontinued,company_id) values ( COMPUTER_SEQ.NEXTVAL,'Apple II Plus',null,null,null);
